// import M from "@/constants/MOCK";
export default Object.freeze({
  sitemap: 0,
  auth: 1,
  login: 0,
  logout: 0,
  register: 0,
  forgot_password: 0,
  reset_password: 0,
  verify_email: 0,
  dashboard: 0,
  drawer: 0,
  app_launcher: 0,
  notifications: 0,
  profile: 1,
  capture: 0,
  members: 1,
  members_create: 0,
  finances: 0,
  test_register: 1,
});
